[tool.poetry]
name = "seed2sale"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{ include = "seed2sale", from = "src" }]

[tool.poetry.dependencies]
python = ">=3.12"
django = ">=5.0.1"
djangorestframework = "^3.16.1"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
